name: Cypress Tests
on: [push]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
            - name: Checkout
              uses: actions/checkout@v3
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  command: npm run ui-regression
              env:
                  USER_MAIL: ${{ secrets.USER_MAIL }}
                  USER_DNI: ${{ secrets.USER_DNI }}
                  USER_CUIT: ${{ secrets.USER_CUIT }}
                  USER_TELEFONO: ${{ secrets.USER_TELEFONO }}
                  USER_CBU: ${{ secrets.USER_CBU }}
            - name: Uploading Artifact
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: cypress-execution-report
                  path: cypress/reports/html
                  retention-days: 30
    slackNotification:
        name: Slack Notification
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                  SLACK_USERNAME: nicomlopez3
                  SLACK_TITLE: UI-Regression Test
                  SLACK_MESSAGE: 'New Changes =D :rocket:'
